version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_sample_data &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=interview_prep
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    command: uvicorn apps.examples.fastapi_examples.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  static_volume:
  media_volume: